# -*- coding: utf-8 -*-
"""fake-real-news-detection_data_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bRG2aWag-3oyWScXyhbe74Bq-iCBBwsW

#Library Imports
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import re
from wordcloud import WordCloud #To visualize the text data

"""#Import Data and Intial Analysis

##Fake News
"""

fake = pd.read_csv('https://raw.githubusercontent.com/mnkd246/fake-news-detection/main/news_dataset/Fake.csv')

fake.head()

fake.columns

fake['subject'].value_counts()

plt.figure(figsize=(10, 6))
palette = sns.color_palette()
sns.countplot(data=fake, x='subject', palette=palette, hue='subject')

"""**Wordcloud**"""

fake['text'].tolist()

"""From the list, it needs to be merged into a single text data"""

text = ' '.join(fake['text'].tolist()) #The ' ' joins the text data with a space (can be comma, etc)

wordcloud = WordCloud(width=1920, height=1080).generate(text)
fig = plt.figure(figsize=(10,10))
plt.imshow(wordcloud)
plt.axis('off')
plt.tight_layout(pad=0)
plt.show()

"""##Real News"""

real = pd.read_csv('https://raw.githubusercontent.com/mnkd246/fake-news-detection/main/news_dataset/True.csv')

text = ' '.join(real['text'].tolist())

wordcloud = WordCloud(width=1920, height=1080).generate(text)
fig = plt.figure(figsize=(10,10))
plt.imshow(wordcloud)
plt.axis('off')
plt.tight_layout(pad=0)
plt.show()

"""One notable difference between fake and real news word clouds is the appearance of "Washington Reuters", which is only on real news. Washington Reuters is very well known news service that provides reports from around the world to newpapers and broadcasters.

So unlike the fake news set, real news is more likely to have a source of publication.

Also, some texts are tweets from Twitter. Some texts don't contain any publication information.
"""